Repository Purple-Print/log-server, pull requests merged in 2022-11, with the labels that each got.

#3 log 기능 - 로그 삭제, 통신 구현중, 분석 api 생성중
  pom.xml
  src/main/java/com/purpleprint/logserver/LogServerApplication.java
  src/main/java/com/purpleprint/logserver/controller/LogController.java
  src/main/java/com/purpleprint/logserver/dto/AnalysisDTO.java
  src/main/java/com/purpleprint/logserver/entity/Analysis.java
  src/main/java/com/purpleprint/logserver/model/LogModel.java
  src/main/java/com/purpleprint/logserver/repository/LogRepository.java
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: ✨New Feature

#4 log 기능 - log 삭제 구현, log 통신 구현중, 분석 api 구현중
  pom.xml
  src/main/java/com/purpleprint/logserver/LogServerApplication.java
  src/main/java/com/purpleprint/logserver/controller/LogController.java
  src/main/java/com/purpleprint/logserver/dto/AnalysisDTO.java
  src/main/java/com/purpleprint/logserver/entity/Analysis.java
  src/main/java/com/purpleprint/logserver/model/LogModel.java
  src/main/java/com/purpleprint/logserver/repository/LogRepository.java
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: ✨New Feature

#5 #1 통신을 위해 로그 조회 임시 수정
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: ✨New Feature

#6 fix: #1 통신을 위해 로그 조회 임시 수정
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: ✨New Feature

#9 fix : #8 timezone default 변경
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: 💥Bug Fix

#10 로그 수집 - 로그 파일 s3 스토리지에 업로드 기능 구현
  pom.xml
  src/main/java/com/purpleprint/logserver/controller/LogController.java
  src/main/java/com/purpleprint/logserver/dto/UploadFileDTO.java
  src/main/java/com/purpleprint/logserver/entity/Logfile.java
  src/main/java/com/purpleprint/logserver/exception/FileEmptyException.java
  src/main/java/com/purpleprint/logserver/repository/AwsS3UploadRepository.java
  src/main/java/com/purpleprint/logserver/service/AwsS3UploadService.java
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: ✨New Feature

#11 Dev -> main 분석 로그 ai서버 연동
  pom.xml
  src/main/java/com/purpleprint/logserver/controller/LogController.java
  src/main/java/com/purpleprint/logserver/dto/FriendsDTO.java
  src/main/java/com/purpleprint/logserver/dto/RequestDTO.java
  src/main/java/com/purpleprint/logserver/entity/Analysis.java
  src/main/java/com/purpleprint/logserver/entity/Logfile.java
  src/main/java/com/purpleprint/logserver/exception/FileEmptyException.java
  src/main/java/com/purpleprint/logserver/repository/AnalysisRepository.java
  src/main/java/com/purpleprint/logserver/repository/AwsS3UploadRepository.java
  src/main/java/com/purpleprint/logserver/service/AwsS3UploadService.java
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: 💥Bug Fix, ✨New Feature

#12 Dev -> main pull request
  pom.xml
  src/main/java/com/purpleprint/logserver/dto/UploadFileDTO.java
  src/main/java/com/purpleprint/logserver/entity/Logfile.java
  src/main/java/com/purpleprint/logserver/exception/FileEmptyException.java
  src/main/java/com/purpleprint/logserver/repository/AwsS3UploadRepository.java
  src/main/java/com/purpleprint/logserver/service/AwsS3UploadService.java
Labels: 💥Bug Fix, ✨New Feature

#13 로그 수집 - #1 logfile db 저장 로직 구현
  src/main/java/com/purpleprint/logserver/controller/LogController.java
  src/main/java/com/purpleprint/logserver/entity/Logfile.java
  src/main/java/com/purpleprint/logserver/repository/LogfileRepository.java
  src/main/java/com/purpleprint/logserver/service/AwsS3UploadService.java
Labels: ✨New Feature

#14 로그 수집 - #1 logfile db 저장 로직 구현
  src/main/java/com/purpleprint/logserver/controller/LogController.java
  src/main/java/com/purpleprint/logserver/entity/Logfile.java
  src/main/java/com/purpleprint/logserver/repository/LogfileRepository.java
  src/main/java/com/purpleprint/logserver/service/AwsS3UploadService.java
Labels: ✨New Feature

#15 test: #1 기능 테스트용 변경
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: ✅Test

#16 테스트
  src/main/java/com/purpleprint/logserver/LogServerApplication.java
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: ✅Test

#18 test: #1 기능 테스트용 변경
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: ✅Test

#19 test: #1 기능 테스트용 변경
  src/main/java/com/purpleprint/logserver/LogServerApplication.java
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: ✅Test

#20 #1 테스트용 변경
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: ✅Test

#21 test: #1 기능 테스트 완료 후 복구
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: ✅Test

#23 elasticsearch 서버 url 수정
  src/main/java/com/purpleprint/logserver/config/ElasticsearchLogConfig.java
Labels: 💥Bug Fix

#25 fix: ai server 형식 변경 수정
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: 💥Bug Fix

#26 fix: ai server 형식 변경 수정
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: 💥Bug Fix

#27 fix: #1 스케쥴링 시간 변경
  src/main/java/com/purpleprint/logserver/controller/LogController.java
Labels: 💥Bug Fix

#28 fix: #1 log send 통신 url 수정
  src/main/java/com/purpleprint/logserver/service/LogService.java
Labels: 💥Bug Fix
